[package]
name = "iwazaki_tcp"
version = "0.1.0"
authors = ["Iwazaki <iwazaki@uta-senzen.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = "0.1.2"
etherparse = "0.9.0"
